# cargo-deny config: `just deny` checks advisories, bans and sources.
# Dependency licences aren't checked; see "Licence" in docs/DESIGN.md's Decisions.

[graph]
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]

[advisories]
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
